export const randomPrompts = [
    "Tell me about yourself.",
    "What's your favorite color?",
    "What's your favorite food?",
    "Coffee.",
    "Are you happy?",
    "Why are you here?",
    "What's the best TV show?",
    "Where do you see yourself in five years?",
    "What's your favorite movie?",
    "Music.",
    "Public speaking.",
    "What's your favorite book?",
    "How's the weather?",
    "Marvel or DC?",
    "Biggest hot take right now?",
    "Trees.",
    "How do you avoid burnout?",
    "What's your most recent project?",
    "What's your favorite project?",
    "What do you do for fun?",
    "What did you do over COVID?",
    "What's your fashion style?",
    "Favorite sports team?",
    "Your theme song?",
    "Family.",
    "Sunrise or sunset?",
    "Ideal vacation?",
    "Sports.",
    "Favorite city?",
    "Why do you want to work here?",
    "How would your friends describe you?",
    "What makes you feel nostalgic?",
    "Video games.",
    "Avocado toast.",
    "What's the best cookie?",
    "Describe your best summer fit.",
    "What was your most recent presentation?",
    "Go-to singing in the shower song?",
    "How do you like your eggs?",
    "Are you a morning person or a night owl?",
    "What's a must-read?",
    "What's something people don't know about you?",
    "The internet.",
    "Pokemon.",
    "How do you want to be remembered?",
    "Sharks.",
    "Space.",
    "What gets you out of bed?",
    "Best Star Wars movie?",
    "Mountains or seas?",
    "If Kirby inhaled you, what superpower would Kirby have?",
    "What do you collect?",
    "What's the one thing that makes you stand out?",
    "What makes you smile?",
    "Cars.",
    "College.",
    "Boston.",
] 